### ISSUE TITLE
Multiple replacement steps in a single rule not working

### ISSUE THREAD

**Issue by caviyacht** [requestly/requestly-issues#25] opened 2018-01-02 21:26 UTC
I'm not entirely sure when it stopped working, but I have a single replacement rule setup that has multiple steps in it.

The first rule is to change the entire url to something different with placeholders based on the requested url. The next 20-ish rules are setup to replace the placeholders with different values.

This used to work and no longer does, it appears that the first rule is firing but then stops.  There are no conditions on any of these right now, just replacements.

If I keep reloading the page, the other replacement steps fire, but only one at a time. So it takes 3 requests for them to all fire.

**Comment by sachinjain024** [comment] 2018-01-03 03:38
Thanks @caviyacht for logging the issue. If I understand you correctly, you have a replace rule with multiple pairs in it and the problem is only first pair is getting fired and remaining pairs are not getting fired. For example:

    Replace q=1 with q=2
    When Url contains example.com

    Replace q=2 with q=3 
    When Url contains example.com

So when user visits, `example.com?q=1`, Ideally he should see `example.com?q=3` because of two pairs in the same rule. Is that similar to your rule ?

## Note
We have lately fixed a bug where multiple rules (redirect, cancel, replace etc) could be fired on same request. Now, with latest change only one rule can modify a request and once a request is modified it is not available to other rules for modification.

**Comment by caviyacht** [comment] 2018-01-03 04:09
@sachinjain024 , thanks for the quick reply. Yes, this is exactly what I am doing, and I can see how that bug fix would cause this to stop working.

I guess how I always took it was that the pairs in a rule would execute together in order, otherwise I do not see a real use in having multiple pairs in a rule.

So if the first pair in a rule matched, then everything else in that rule is ok to execute. Was this the intended behavior? That way the multiple-rule execution prevention logic can still be in place, but a let a single rule do multiple things to a request.

**Comment by sachinjain024** [comment] 2018-01-03 05:12
@caviyacht Yes, I am able to reproduce the issue. Currently, first pair is getting executed only and then rest of the pairs are not getting executed. This is certainly a bug.

Pairs in a single rule allows users to perform multiple actions on a given request. Performing multiple rules on a single request makes things complex for debugging and understanding what is happening exactly.

I will try to fix this by EOD IST.

**Comment by sachinjain024** [comment] 2018-01-04 15:45
@caviyacht We have fixed this issue. Please allow us a couple of days to deploy the extension to chrome store and firefox server.

**Comment by requestlyext** [comment] 2018-01-07 06:43
@caviyacht We have fixed this issue and deployed v5.1.3 in chrome store. It should be available in half an hour or so. Thanks for your patience.

**Comment by sachinjain024** [comment] 2018-01-15 05:29
Looks like the issue is fixed so closing this one.

**Closed by sachinjain024** 2018-01-15 05:29 UTC
