### ISSUE TITLE
blogspot.com image not show with center image

### ISSUE THREAD

**Issue by DandyClubs** [requestly/requestly-issues#8] opened 2017-03-16 21:42 UTC
firefox 52.0 x64 and center image
https://greasyfork.org/en/scripts/110-center-image

https://4.bp.blogspot.com/-uNpXrGANwPs/WLDG9jnO2iI/AAAAAAAALPs/WDgHwA4ST4QXxPWe-LcYR0tHj6ORCjZ2gCLcB/s1600/MMR-AK032.jpeg

 image is no show

image is show when reload (f5)

chrome is fine but firefox need reload 

only image is show when disable requestly 4.2.10 or disable center image script

**Comment by sachinjain024** [comment] 2017-03-17 05:01
Thanks @DandyClubs for logging this. I will take a look at this soon.

**Comment by sachinjain024** [comment] 2017-07-11 04:20
@DandyClubs Sorry for delay on this but I could not reproduce this issue. Closing this. Feel free to reopen if you are still facing this.

**Closed by sachinjain024** 2017-07-11 04:20 UTC
