### ISSUE TITLE
Can't use Chinese Rule Name

### ISSUE THREAD

**Issue by bestpika** [requestly/requestly-issues#21] opened 2017-12-14 16:10 UTC
![image](https://user-images.githubusercontent.com/5698157/34001952-591cf9c6-e12c-11e7-90c2-0878d7d2de2a.png)

**Comment by sachinjain024** [comment] 2018-06-01 08:09
Thanks @Cologler. I also tried to reproduce the issue but was unable to do so. Closing this issue as "Unable to Reproduce"

**Closed by sachinjain024** 2018-06-01 08:09 UTC
